import { Scene } from 'phaser';

/** Loads the placeholder tileset and the Tiled map generated by `pnpm placeholders`. */
export class Preloader extends Scene {
  constructor() {
    super('Preloader');
  }

  preload() {
    const bar = this.add.rectangle(240, 135, 4, 6, 0xc9a66b);
    this.load.on('progress', (p: number) => {
      bar.width = 4 + 200 * p;
    });
    this.load.setPath('assets/placeholder');
    this.load.image('placeholder-tiles', 'tileset.png');
    this.load.tilemapTiledJSON('town', 'town.json');
  }

  create() {
    this.scene.start('Town');
  }
}
