// Characters on the shared 16×32 grid (PROMPT.md §4.4, GAME-LAYER.md §5): a body drawn once in
// region codes, hair styles as overlays, both recoloured per person. Four directions, four walk
// frames each; right-facing frames are the left-facing ones mirrored.
import { SKIN, TRIO, type SkinName, type TrioName } from './palette.ts';
import { blank, blit, flipH, px, recolor, stack, type Pixmap } from './pixmap.ts';

// Region codes: o outline · s skin · S skin shadow · E eye · m mouth · t top · T top shadow ·
// U top highlight · p bottom · P bottom shadow · b shoe · B shoe shadow · n neck shadow
const BODY_LEGEND = {
  o: 'ink',
  s: 'SKIN',
  S: 'SKIN_SH',
  E: 'EYE',
  m: 'MOUTH',
  t: 'TOP',
  T: 'TOP_SH',
  U: 'TOP_HI',
  p: 'BOT',
  P: 'BOT_SH',
  b: 'SHOE',
  B: 'SHOE_SH',
  n: 'SKIN_SH',
};

const body = (rows: string) => px(rows, BODY_LEGEND);

// ---- facing down ----
const DOWN_0 = body(`
  ................
  ................
  .....oooooo.....
  ....osssssso....
  ...ossssssssso..
  ...ossssssssso..
  ...ossssssssso..
  ...ossssssssso..
  ...osEssssEsso..
  ...osossssosso..
  ...ossssssssso..
  ...oSsssmmsssSo.
  ....oSssssssSo..
  .....ooSSSSoo...
  ......onSSno....
  ....oUtttttTTo..
  ..ooUtttttttToo.
  .oUtUtttttttTTo.
  .oUtottttttoTTo.
  .oUtottttttoTTo.
  .oUtottttttoTTo.
  .oUtotTTTTToTTo.
  .osSopppppppoSo.
  .oSSopPpppPpoSo.
  ..ooopPpppPpooo.
  ....opPppppPpo..
  ....opPpooPpPo..
  ....opPpo.oPpo..
  ....opPpo.oPpo..
  ....obbbo.obbbo.
  ...obbbB.obbbBo.
  ...ooooo.oooooo.`);

const DOWN_1 = body(`
  ................
  .....oooooo.....
  ....osssssso....
  ...ossssssssso..
  ...ossssssssso..
  ...ossssssssso..
  ...ossssssssso..
  ...osEssssEsso..
  ...osossssosso..
  ...ossssssssso..
  ...oSsssmmsssSo.
  ....oSssssssSo..
  .....ooSSSSoo...
  ......onSSno....
  ....oUtttttTTo..
  ..ooUtttttttToo.
  .oUtUtttttttTTo.
  .oUtottttttoTTo.
  .oUtottttttoTTo.
  .oUtottttttoTTo.
  .osSotTTTTToTTo.
  .oSSopppppppoSo.
  ..ooopPpppPpooo.
  ....opPppppPpo..
  ....opPpooPpPo..
  ....opPpo.oPpo..
  ....opPpo.oPpo..
  ....obbbo.oPpo..
  ...obbbBo.obbbo.
  ...oooooo.obbBo.
  ..........ooooo.
  ................`);

// ---- facing up (back of the head; the hair overlay fills the crown) ----
const UP_0 = body(`
  ................
  ................
  .....oooooo.....
  ....osssssso....
  ...ossssssssso..
  ...ossssssssso..
  ...ossssssssso..
  ...ossssssssso..
  ...ossssssssso..
  ...ossssssssso..
  ...ossssssssso..
  ...oSsssssssSo..
  ....oSssssssSo..
  .....ooSSSSoo...
  ......onSSno....
  ....oUtttttTTo..
  ..ooUtttttttToo.
  .oUtUtttttttTTo.
  .oUtottttttoTTo.
  .oUtottttttoTTo.
  .oUtottttttoTTo.
  .oUtottttttoTTo.
  .osSopppppppoSo.
  .oSSopPpppPpoSo.
  ..ooopPpppPpooo.
  ....opPppppPpo..
  ....opPpooPpPo..
  ....opPpo.oPpo..
  ....opPpo.oPpo..
  ....obbbo.obbbo.
  ...oBbbb.oBbbbo.
  ...ooooo.oooooo.`);

const UP_1 = body(`
  ................
  .....oooooo.....
  ....osssssso....
  ...ossssssssso..
  ...ossssssssso..
  ...ossssssssso..
  ...ossssssssso..
  ...ossssssssso..
  ...ossssssssso..
  ...ossssssssso..
  ...oSsssssssSo..
  ....oSssssssSo..
  .....ooSSSSoo...
  ......onSSno....
  ....oUtttttTTo..
  ..ooUtttttttToo.
  .oUtUtttttttTTo.
  .oUtottttttoTTo.
  .oUtottttttoTTo.
  .oUtottttttoTTo.
  .osSottttttoTTo.
  .oSSopppppppoSo.
  ..ooopPpppPpooo.
  ....opPppppPpo..
  ....opPpooPpPo..
  ....opPpo.oPpo..
  ....opPpo.oPpo..
  ....obbbo.oPpo..
  ...oBbbbo.obbbo.
  ...oooooo.oBbbo.
  ..........ooooo.
  ................`);

// ---- facing left (mirrored for right) ----
const LEFT_0 = body(`
  ................
  ................
  .....oooooo.....
  ....ossssssso...
  ...osssssssssso.
  ...osssssssssso.
  ...osssssssssso.
  ...osssssssssso.
  ...osEsssssssso.
  ...ososssssssso.
  ..oSsssssssssso.
  ..oSmsssssssSo..
  ...oSsssssssSo..
  ....ooSSSSSoo...
  ......oSSno.....
  .....otttttTo...
  ....otUtttTTTo..
  ....otUtttTTTo..
  ....otoUtoTTTo..
  ....otoUtoTTTo..
  ....otoUtoTTTo..
  ....otoTtoTTTo..
  ....oSoppoPpSo..
  ....oSoppoPpSo..
  .....oppppPPo...
  .....opppPPPo...
  .....oppoPPPo...
  .....oppo.PPo...
  .....oppo.PPo...
  ....obbbo.oBbo..
  ...obbbbo.oBbbo.
  ...ooooo..ooooo.`);

const LEFT_1 = body(`
  ................
  .....oooooo.....
  ....ossssssso...
  ...osssssssssso.
  ...osssssssssso.
  ...osssssssssso.
  ...osssssssssso.
  ...osEsssssssso.
  ...ososssssssso.
  ..oSsssssssssso.
  ..oSmsssssssSo..
  ...oSsssssssSo..
  ....ooSSSSSoo...
  ......oSSno.....
  .....otttttTo...
  ....otUtttTTTo..
  ....otUtttTTTo..
  ....otoUtoTTTo..
  ....otoUtoTTTo..
  ....otoUtoTTTo..
  ....oSoTtoTTSo..
  ....oSoppoPpSo..
  .....oppppPPo...
  .....opppPPPo...
  ....oppoPPPo....
  ...oppo.oPPPo...
  ..oppo...oPPo...
  ..oppo....oPPo..
  .obbbo.....oBbo.
  .obbbbo...oBbbo.
  .ooooo....ooooo.
  ................`);

const LEFT_3 = body(`
  ................
  .....oooooo.....
  ....ossssssso...
  ...osssssssssso.
  ...osssssssssso.
  ...osssssssssso.
  ...osssssssssso.
  ...osEsssssssso.
  ...ososssssssso.
  ..oSsssssssssso.
  ..oSmsssssssSo..
  ...oSsssssssSo..
  ....ooSSSSSoo...
  ......oSSno.....
  .....otttttTo...
  ....otUtttTTTo..
  ....otUtttTTTo..
  ....otoUtoTTTo..
  ....otoUtoTTTo..
  ....otoUtoTTTo..
  ....oSoTtoTTSo..
  ....oSoppoPpSo..
  .....oppppPPo...
  .....opppPPPo...
  ......oppPPPo...
  .....oPPpoPPo...
  ....oPPpo.oPPo..
  ...oPPpo..oPPo..
  ..oBbbo....obbo.
  ..oBbbbo..obbbo.
  ..ooooo...ooooo.
  ................`);

export type Dir = 'down' | 'up' | 'left' | 'right';
export const DIRS: Dir[] = ['down', 'up', 'left', 'right'];

/** The standing frame with head and torso settled one pixel lower: the second idle-breathe frame. */
function breathe(stand: Pixmap): Pixmap {
  const out = blank(16, 32);
  for (let y = 1; y <= 25; y++)
    for (let x = 0; x < 16; x++) out.px[y * 16 + x] = stand.px[(y - 1) * 16 + x]!;
  for (let y = 25; y < 32; y++)
    for (let x = 0; x < 16; x++)
      if (stand.px[y * 16 + x]) out.px[y * 16 + x] = stand.px[y * 16 + x]!;
  return out;
}

/** Five frames per direction: walk 0–3 (stand, step, stand, other step) and 4 = breathe. */
export const BODY_FRAMES: Record<Dir, Pixmap[]> = {
  down: [DOWN_0, DOWN_1, DOWN_0, flipH(DOWN_1), breathe(DOWN_0)],
  up: [UP_0, UP_1, UP_0, flipH(UP_1), breathe(UP_0)],
  left: [LEFT_0, LEFT_1, LEFT_0, LEFT_3, breathe(LEFT_0)],
  right: [flipH(LEFT_0), flipH(LEFT_1), flipH(LEFT_0), flipH(LEFT_3), breathe(flipH(LEFT_0))],
};
export const FRAMES_PER_DIR = 5;

// ---- hair -----------------------------------------------------------------------------------
// Hair overlays cover rows 0–15 of the frame. h main · H shadow · L highlight · o outline.
const HAIR_LEGEND = { h: 'HAIR', H: 'HAIR_SH', L: 'HAIR_HI', o: 'ink' };
const hair = (rows: string) => px(rows, HAIR_LEGEND);

export type HairStyle =
  'crop' | 'side-part' | 'bob' | 'long' | 'ponytail' | 'bun' | 'curly' | 'slick' | 'balding';

interface HairSet {
  down: Pixmap;
  up: Pixmap;
  left: Pixmap;
}

const HAIR: Record<HairStyle, HairSet> = {
  crop: {
    down: hair(`
      ................
      ................
      .....oooooo.....
      ....oLLhhhho....
      ...oLLhhhhhHo...
      ...ohhhhhhhHo...
      ...ohhhhhhhHo...
      ...oHhhhhhhHo...
      ....oHhhhhHo....
      ................
      ................
      ................
      ................
      ................
      ................
      ................`),
    up: hair(`
      ................
      ................
      .....oooooo.....
      ....oLLhhhho....
      ...oLLhhhhhHo...
      ...ohhhhhhhHo...
      ...ohhhhhhhHo...
      ...ohhhhhhhHo...
      ...oHhhhhhhHo...
      ...oHhhhhhhHo...
      ....oHHhhHHo....
      ................
      ................
      ................
      ................
      ................`),
    left: hair(`
      ................
      ................
      .....oooooo.....
      ....oLLhhhhho...
      ...oLLhhhhhhHo..
      ...ohhhhhhhhHo..
      ...ohhhhhhhhHo..
      ...oHhhhhhhhHo..
      ....oHHhhhhHo...
      ........oHHo....
      ................
      ................
      ................
      ................
      ................
      ................`),
  },
  'side-part': {
    down: hair(`
      ................
      ................
      .....oooooo.....
      ....oLLhhhho....
      ...oLLhhhhhHo...
      ...ohLhhhhhHo...
      ...ohhhhhhhHHo..
      ...ohhhhoHHHHo..
      ...oHHHo..oHHo..
      ....oo.....oo...
      ................
      ................
      ................
      ................
      ................
      ................`),
    up: hair(`
      ................
      ................
      .....oooooo.....
      ....oLLhhhho....
      ...oLLhhhhhHo...
      ...ohhhhhhhHo...
      ...ohhhhhhhHo...
      ...ohhhhhhhHo...
      ...oHhhhhhhHo...
      ...oHhhhhhhHo...
      ....oHHhhHHo....
      ................
      ................
      ................
      ................
      ................`),
    left: hair(`
      ................
      ................
      .....oooooo.....
      ....oLLhhhhho...
      ...oLLhhhhhhHo..
      ...ohhhhhhhhHo..
      ...ohhhhhhhhHo..
      ...oHhhhhoHHHo..
      ....oHHHo.oHHo..
      .....oo..oHHo...
      ..........oo....
      ................
      ................
      ................
      ................
      ................`),
  },
  bob: {
    down: hair(`
      ................
      ................
      .....oooooo.....
      ....oLLhhhho....
      ...oLLhhhhhHo...
      ...ohhhhhhhHo...
      ...ohhhhhhhHo...
      ...ohHHHHHHHo...
      ...oho....oHo...
      ...oho....oHo...
      ...oho....oHo...
      ...oho....oHo...
      ...oHo....oHo...
      ...oHHo..oHHo...
      ....oo....oo....
      ................`),
    up: hair(`
      ................
      ................
      .....oooooo.....
      ....oLLhhhho....
      ...oLLhhhhhHo...
      ...ohhhhhhhHo...
      ...ohhhhhhhHo...
      ...ohhhhhhhHo...
      ...ohhhhhhhHo...
      ...ohhhhhhhHo...
      ...ohhhhhhhHo...
      ...ohhhhhhhHo...
      ...oHhhhhhhHo...
      ...oHHhhhhHHo...
      ....oooooooo....
      ................`),
    left: hair(`
      ................
      ................
      .....oooooo.....
      ....oLLhhhhho...
      ...oLLhhhhhhHo..
      ...ohhhhhhhhHo..
      ...ohhhhhhhhHo..
      ...oHHhhhhhhHo..
      ....ooohhhhhHo..
      ......ohhhhhHo..
      ......ohhhhhHo..
      ......ohhhhHHo..
      ......oHhhHHHo..
      ......oHHHHHo...
      .......ooooo....
      ................`),
  },
  long: {
    down: hair(`
      ................
      ................
      .....oooooo.....
      ....oLLhhhho....
      ...oLLhhhhhHo...
      ...ohhhhhhhHo...
      ...ohhhhhhhHo...
      ...ohHHHHHHHo...
      ...oho....oHo...
      ...oho....oHo...
      ...oho....oHo...
      ...oho....oHo...
      ...oho....oHo...
      ...oho....oHo...
      ...oho....oHo...
      ...oHo....oHo...`),
    up: hair(`
      ................
      ................
      .....oooooo.....
      ....oLLhhhho....
      ...oLLhhhhhHo...
      ...ohhhhhhhHo...
      ...ohhhhhhhHo...
      ...ohhhhhhhHo...
      ...ohhhhhhhHo...
      ...ohhhhhhhHo...
      ...ohhhhhhhHo...
      ...ohhhhhhhHo...
      ...ohhhhhhhHo...
      ...ohhhhhhhHo...
      ...oHhhhhhhHo...
      ...oHHhhhhHHo...`),
    left: hair(`
      ................
      ................
      .....oooooo.....
      ....oLLhhhhho...
      ...oLLhhhhhhHo..
      ...ohhhhhhhhHo..
      ...ohhhhhhhhHo..
      ...oHHhhhhhhHo..
      ....ooohhhhhHo..
      ......ohhhhhHo..
      ......ohhhhhHo..
      ......ohhhhhHo..
      ......ohhhhhHo..
      ......ohhhhhHo..
      ......oHhhhHHo..
      ......oHHHHHHo..`),
  },
  ponytail: {
    down: hair(`
      ................
      ................
      .....oooooo.....
      ....oLLhhhho....
      ...oLLhhhhhHo...
      ...ohhhhhhhHo...
      ...ohhhhhhhHo...
      ...oHhhhhhhHo...
      ....oHhhhhHo....
      ................
      ................
      ................
      ................
      ................
      ................
      ................`),
    up: hair(`
      ................
      ................
      .....oooooo.....
      ....oLLhhhho....
      ...oLLhhhhhHo...
      ...ohhhhhhhHo...
      ...ohhhhhhhHo...
      ...ohhhhhhhHo...
      ...oHhhhHhhHo...
      ...oHhhoHohHo...
      ....oHoHHHoHo...
      .....ooHHHoo....
      ......oHHHo.....
      ......oHHHo.....
      ......oHHHo.....
      .......oHo......`),
    left: hair(`
      ................
      ................
      .....oooooo.....
      ....oLLhhhhho...
      ...oLLhhhhhhHo..
      ...ohhhhhhhhHo..
      ...ohhhhhhhhHo..
      ...oHhhhhhhhHo..
      ....oHHhhhhHHo..
      ........oHHHHHo.
      .........oHHHo..
      .........oHHHo..
      ..........oHo...
      ..........oHo...
      ...........o....
      ................`),
  },
  bun: {
    down: hair(`
      ................
      ................
      .....oooooooo...
      ....oLLhhhhLhHo.
      ...oLLhhhhhoHHo.
      ...ohhhhhhhhooo.
      ...ohhhhhhhHo...
      ...oHhhhhhhHo...
      ....oHhhhhHo....
      ................
      ................
      ................
      ................
      ................
      ................
      ................`),
    up: hair(`
      ................
      ................
      .....oooooooo...
      ....oLLhhhhLhHo.
      ...oLLhhhhhoHHo.
      ...ohhhhhhhhooo.
      ...ohhhhhhhHo...
      ...ohhhhhhhHo...
      ...oHhhhhhhHo...
      ...oHhhhhhhHo...
      ....oHHhhHHo....
      ................
      ................
      ................
      ................
      ................`),
    left: hair(`
      ................
      ................
      .....ooooooooo..
      ....oLLhhhhLhHo.
      ...oLLhhhhhhHHo.
      ...ohhhhhhhhooo.
      ...ohhhhhhhhHo..
      ...oHhhhhhhhHo..
      ....oHHhhhhHo...
      ........oHHo....
      ................
      ................
      ................
      ................
      ................
      ................`),
  },
  curly: {
    down: hair(`
      ................
      ................
      ......oo..oo....
      ....oohhoohhoo..
      ...oLLhhhhhhhHo.
      ..ooLhhhhhhhHoo.
      ..ohhhhhhhhhhHo.
      ..oHhhhhhhhhHHo.
      ..ooHhhhhhhHHoo.
      ...oHHHoooHHHo..
      ....oo....oo....
      ................
      ................
      ................
      ................
      ................`),
    up: hair(`
      ................
      ................
      ......oo..oo....
      ....oohhoohhoo..
      ...oLLhhhhhhhHo.
      ..ooLhhhhhhhHoo.
      ..ohhhhhhhhhhHo.
      ..ohhhhhhhhhhHo.
      ..oHhhhhhhhhHHo.
      ..ooHhhhhhhHHoo.
      ...oHHhhhhhhHHo.
      ....ooHHHHHHoo..
      ......oooooo....
      ................
      ................
      ................`),
    left: hair(`
      ................
      ................
      ......oo..oo....
      ....oohhoohhoo..
      ...oLLhhhhhhhHo.
      ..ooLhhhhhhhHoo.
      ..ohhhhhhhhhhHo.
      ..oHhhhhhhhhHHo.
      ..ooHHhhhhhHHoo.
      ....oooHhhhHHo..
      .......oHHHHo...
      ........oooo....
      ................
      ................
      ................
      ................`),
  },
  slick: {
    down: hair(`
      ................
      ................
      .....oooooo.....
      ....oLhLhhho....
      ...oLhLhhhhHo...
      ...ohLhhhhhHo...
      ...ohhhhhhhHo...
      ....oHhhhhHo....
      .....oooooo.....
      ................
      ................
      ................
      ................
      ................
      ................
      ................`),
    up: hair(`
      ................
      ................
      .....oooooo.....
      ....oLhLhhho....
      ...oLhLhhhhHo...
      ...ohLhhhhhHo...
      ...ohhhhhhhHo...
      ...ohhhhhhhHo...
      ...oHhhhhhhHo...
      ...oHhhhhhhHo...
      ....oHHhhHHo....
      ................
      ................
      ................
      ................
      ................`),
    left: hair(`
      ................
      ................
      .....oooooo.....
      ....oLhLhhhho...
      ...oLhLhhhhhHo..
      ...ohLhhhhhhHo..
      ...ohhhhhhhhHo..
      ....oHhhhhhhHo..
      .....ooooHHHo...
      .........oHHo...
      ..........oo....
      ................
      ................
      ................
      ................
      ................`),
  },
  balding: {
    down: hair(`
      ................
      ................
      ................
      ................
      ................
      ....oo......oo..
      ...ohHo....oHho.
      ...ohHo....oHho.
      ...oHHo....oHHo.
      ....oo......oo..
      ................
      ................
      ................
      ................
      ................
      ................`),
    up: hair(`
      ................
      ................
      ................
      ................
      ................
      ....oo......oo..
      ...ohHo....oHho.
      ...ohHoooooHHho.
      ...oHHhhhhhhHHo.
      ....oHHhhhhHHo..
      .....oooooooo...
      ................
      ................
      ................
      ................
      ................`),
    left: hair(`
      ................
      ................
      ................
      ................
      ................
      ...........oo...
      ..........oHho..
      .........ooHHo..
      ........oHHHHo..
      .........oooo...
      ................
      ................
      ................
      ................
      ................
      ................`),
  },
};

// ---- accessories ----------------------------------------------------------------------------
export type Accessory = 'glasses' | 'headset' | 'tie' | 'glasses-up' | 'none';

const ACC_LEGEND = { o: 'ink', g: 'gold', b: 'bone', k: 'slate-dark', r: 'brick', w: 'ink@140' };
const ACC: Record<
  Exclude<Accessory, 'none'>,
  { down?: Pixmap; left?: Pixmap; up?: Pixmap; onBody?: boolean }
> = {
  glasses: {
    down: px(
      `
      ................
      ................
      ................
      ................
      ................
      ................
      ................
      ....ooo.ooo.....
      ...ok.kok.ko....
      ....ooo.ooo.....
      ................
      ................
      ................
      ................
      ................
      ................`,
      ACC_LEGEND,
    ),
    left: px(
      `
      ................
      ................
      ................
      ................
      ................
      ................
      ................
      ...oooo.........
      ..ok.kooo.......
      ...ooo..........
      ................
      ................
      ................
      ................
      ................
      ................`,
      ACC_LEGEND,
    ),
  },
  'glasses-up': {
    down: px(
      `
      ................
      ................
      ................
      ....ooo.ooo.....
      ...okkkokkko....
      ....ooo.ooo.....
      ................
      ................
      ................
      ................
      ................
      ................
      ................
      ................
      ................
      ................`,
      ACC_LEGEND,
    ),
    left: px(
      `
      ................
      ................
      ................
      ...oooo.........
      ..okkkoooo......
      ...ooo..........
      ................
      ................
      ................
      ................
      ................
      ................
      ................
      ................
      ................
      ................`,
      ACC_LEGEND,
    ),
  },
  headset: {
    down: px(
      `
      ................
      ................
      ................
      ...k........k...
      ..kk........kk..
      ..kk........kk..
      ..kk........kk..
      ..kk........kk..
      ...k........k...
      ................
      ..........kk....
      ................
      ................
      ................
      ................
      ................`,
      ACC_LEGEND,
    ),
    left: px(
      `
      ................
      ................
      ....kkkkkkk.....
      ...k.......k....
      ...k.......k....
      ..kk.......k....
      ..kk............
      ..kk............
      ..kk............
      ...k............
      ....kk..........
      ................
      ................
      ................
      ................
      ................`,
      ACC_LEGEND,
    ),
    up: px(
      `
      ................
      ................
      ....kkkkkkkk....
      ...k........k...
      ..kk........kk..
      ..kk........kk..
      ..kk........kk..
      ..kk........kk..
      ...k........k...
      ................
      ................
      ................
      ................
      ................
      ................
      ................`,
      ACC_LEGEND,
    ),
  },
  tie: {
    onBody: true,
    down: px(
      `
      ................
      ................
      ................
      ................
      ................
      ................
      ................
      ................
      ................
      ................
      ................
      ................
      ................
      ................
      ................
      .......rr.......
      .......rr.......
      .......rr.......
      .......rr.......
      ......rrrr......
      ......rrrr......
      .......rr.......
      ................
      ................
      ................
      ................
      ................
      ................
      ................
      ................
      ................
      ................`,
      ACC_LEGEND,
    ),
  },
};

// ---- a person -------------------------------------------------------------------------------

export interface Look {
  skin: SkinName;
  hair: HairStyle;
  hairColor: TrioName;
  eyes: string;
  top: TrioName;
  bottom: TrioName;
  shoes: string;
  accessory?: Accessory;
}

function paint(body: Pixmap, look: Look): Pixmap {
  const [sS, s] = SKIN[look.skin];
  const [tS, t, tH] = TRIO[look.top];
  const [bS, b] = TRIO[look.bottom];
  return recolor(body, {
    SKIN: s,
    SKIN_SH: sS,
    EYE: look.eyes,
    MOUTH: sS,
    TOP: t,
    TOP_SH: tS,
    TOP_HI: tH,
    BOT: b,
    BOT_SH: bS,
    SHOE: look.shoes,
    SHOE_SH: 'ink',
  });
}

function paintHair(h: Pixmap, look: Look): Pixmap {
  const [sh, main, hi] = TRIO[look.hairColor];
  return recolor(h, { HAIR: main, HAIR_SH: sh, HAIR_HI: hi });
}

/** One frame: body, hair and accessory for a direction and walk frame, with the step bob. */
export function frame(look: Look, dir: Dir, n: number): Pixmap {
  const bodyPic = BODY_FRAMES[dir][n % FRAMES_PER_DIR]!;
  const set = HAIR[look.hair];
  const hairView =
    dir === 'down' ? set.down : dir === 'up' ? set.up : dir === 'left' ? set.left : flipH(set.left);
  const bob = n === 4 ? 1 : n % 2 === 1 ? -1 : 0;
  const out = blank(16, 32);
  blit(out, paint(bodyPic, look), 0, 0);
  blit(out, paintHair(hairView, look), 0, bob);
  const acc = look.accessory && look.accessory !== 'none' ? ACC[look.accessory] : undefined;
  if (acc) {
    const view = acc.onBody
      ? dir === 'down'
        ? acc.down
        : undefined
      : dir === 'down'
        ? acc.down
        : dir === 'up'
          ? acc.up
          : dir === 'left'
            ? acc.left
            : acc.left && flipH(acc.left);
    if (view) blit(out, view, 0, acc.onBody ? bob : bob);
  }
  return out;
}

export const HAIR_STYLES = Object.keys(HAIR) as HairStyle[];
export const _c = { stack };
