// Props and plants: trees, bushes, rocks, fences, lamps, the well, the Ledger Bin, signs, the
// ferry, the derelict windmill, the Vault arch. Light from the upper left; one shade of shadow;
// selective dark outlines (GAME-LAYER.md §5 rule 1).
import { RAMPS, type Ramp } from './palette.ts';
import {
  applyRamp,
  blank,
  blit,
  fillCircle,
  fillEllipse,
  fillRect,
  flipH,
  get,
  outlineInside,
  px,
  set,
  shaded,
  stack,
  type Pixmap,
} from './pixmap.ts';

const SHADOW = 'ink@70';

// ---- foliage ------------------------------------------------------------------------------

interface Blob {
  cx: number;
  cy: number;
  r: number;
}

/**
 * A leaf canopy from overlapping clumps. Each pixel takes the uppermost clump that covers it,
 * shaded by its position on that clump (lit top-left), with a darker line where a lower clump
 * disappears under it, then a one-pixel inside outline.
 */
export function canopy(w: number, h: number, blobs: Blob[], ramp: Ramp = RAMPS.leaf): Pixmap {
  const p = blank(w, h);
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const inside = blobs.filter(
        (b) => (x + 0.5 - b.cx) ** 2 + (y + 0.5 - b.cy) ** 2 <= b.r * b.r,
      );
      if (inside.length === 0) continue;
      const top = inside.reduce((a, b) => (b.cy < a.cy ? b : a));
      const lx = (x + 0.5 - top.cx) / top.r;
      const ly = (y + 0.5 - top.cy) / top.r;
      const lit = -lx * 0.55 - ly;
      let shade = lit > 0.5 ? 'R5' : lit > 0.05 ? 'R4' : lit > -0.5 ? 'R3' : 'R2';
      // clump edge: this pixel sits on another clump's rim, in that clump's lower-right half
      for (const b of inside) {
        if (b === top) continue;
        const d = Math.hypot(x + 0.5 - b.cx, y + 0.5 - b.cy);
        if (d > b.r - 1.3 && b.cy > top.cy - 0.5 && lx + ly > -0.3) shade = 'R2';
      }
      p.px[y * w + x] = shade;
    }
  }
  return applyRamp(outlineInside(p, 'R1'), ramp);
}

const OAK_TRUNK = px(
  `
  ....ACBBA...
  ...ACCBBBA..
  ...ACCBBBA..
  ...ACCBBBA..
  ...ACCBBBA..
  ...ACCBBBA..
  ...ACCBBBA..
  ...ACCBBBA..
  ...ACCBBBA..
  ...ACCBBBA..
  ...ACCBBBA..
  ..ACCCBBBBA.
  ..ACCCBBBBA.
  .ACCCCBBBBBA
  ACCCCBBBBBBA
  AAAAAAAAAAAA`,
  { A: 'bark-dark', B: 'bark', C: 'timber' },
);

/** A broadleaf tree, 48×64: canopy in the `above` layer, trunk and shadow below. */
export function oak(seed = 0): Pixmap {
  const p = blank(48, 64);
  fillEllipse(p, 24, 61, 12, 3, SHADOW);
  blit(p, OAK_TRUNK, 18, 46);
  const j = (seed % 3) - 1;
  const leaves = canopy(48, 48, [
    { cx: 24 + j, cy: 17, r: 15 },
    { cx: 11, cy: 24, r: 11 },
    { cx: 37, cy: 24 - j, r: 11 },
    { cx: 24, cy: 31, r: 13 },
    { cx: 15 + j, cy: 12, r: 9 },
    { cx: 33, cy: 11, r: 9 },
  ]);
  return blit(p, leaves, 0, 0);
}

/** An orchard tree, 32×48, with fruit in the lit leaves. */
export function fruitTree(fruit: string, seed = 0): Pixmap {
  const p = blank(32, 48);
  fillEllipse(p, 16, 45, 8, 2, SHADOW);
  blit(
    p,
    px(`.ACBA.\n.ACBA.\n.ACBA.\n.ACBA.\nACCBBA\nAAAAAA`, {
      A: 'bark-dark',
      B: 'bark',
      C: 'timber',
    }),
    13,
    38,
  );
  const leaves = canopy(32, 36, [
    { cx: 16, cy: 14, r: 12 },
    { cx: 8, cy: 20, r: 8 },
    { cx: 24, cy: 20, r: 8 },
    { cx: 16, cy: 24, r: 9 },
  ]);
  const spots = [
    [10, 12],
    [20, 10],
    [14, 22],
    [24, 24],
    [7, 24],
    [19, 18],
  ];
  spots.forEach(([x, y], i) => {
    if ((i + seed) % 5 === 4) return;
    if (get(leaves, x!, y!)) set(leaves, x!, y!, fruit);
  });
  return blit(p, leaves, 0, 0);
}

/** A conifer, 32×64: three tiers lit from the left. */
export function pine(): Pixmap {
  const p = blank(32, 64);
  fillEllipse(p, 16, 61, 8, 2, SHADOW);
  blit(
    p,
    px(`.ACBA.\n.ACBA.\n.ACBA.\n.ACBA.\n.ACBA.\nACCBBA\nAAAAAA`, {
      A: 'bark-dark',
      B: 'bark',
      C: 'timber',
    }),
    13,
    51,
  );
  const tiers: [number, number, number][] = [
    [2, 22, 14],
    [14, 36, 20],
    [28, 52, 26],
  ];
  const leaves = blank(32, 56);
  for (const [y0, y1, w] of tiers) {
    for (let y = y0; y < y1; y++) {
      const half = ((w / 2) * (y - y0 + 2)) / (y1 - y0);
      for (let x = 0; x < 32; x++) {
        const dx = x + 0.5 - 16;
        if (Math.abs(dx) > half) continue;
        const t = dx / Math.max(half, 1);
        let shade = t < -0.25 ? 'R4' : t > 0.45 ? 'R2' : 'R3';
        if (y >= y1 - 2) shade = 'R2';
        if (y < y0 + 2 && t < 0.2) shade = 'R5';
        set(leaves, x, y, shade);
      }
    }
  }
  return blit(p, applyRamp(outlineInside(leaves, 'R1'), RAMPS.leaf), 0, 0);
}

export function bush(): Pixmap {
  const p = blank(16, 16);
  fillEllipse(p, 8, 14, 7, 1.5, SHADOW);
  const leaves = canopy(16, 14, [
    { cx: 5, cy: 9, r: 5 },
    { cx: 11, cy: 9, r: 5 },
    { cx: 8, cy: 6, r: 5 },
  ]);
  return blit(p, leaves, 0, 1);
}

const F = {
  c: 'moss',
  d: 'grass',
  e: 'grass-light',
  v: 'lantern',
  u: 'gold',
  O: 'lavender',
  N: 'plum',
  r: 'peach',
  x: 'cream',
  q: 'terracotta',
};
export const FLOWERS: Pixmap[] = [
  px(
    `
    ................
    ................
    ................
    ....v...........
    ...vuv..........
    ....v......v....
    ....c.....vuv...
    ....c......v....
    ..........cc....
    ................
    ........v.......
    .......vuv......
    ........v.......
    ........c.......
    ................
    ................`,
    F,
  ),
  px(
    `
    ................
    ................
    .....O..........
    ....OvO.........
    .....O.....O....
    .....c....OvO...
    ..........cO....
    ..........c.....
    ................
    ....O...........
    ...OvO..........
    ....O......O....
    ....c.....OvO...
    ...........O....
    ...........c....
    ................`,
    F,
  ),
  px(
    `
    ................
    ................
    ................
    ......r.........
    .....rxr........
    ......r....r....
    ......c...rxr...
    ...........r....
    ...........c....
    ................
    ...r............
    ..rxr...........
    ...r............
    ...c............
    ................
    ................`,
    F,
  ),
];

export const TUFTS: Pixmap[] = [
  px(
    `
    ................
    ................
    ................
    ................
    ................
    ........e.......
    ....e...e..e....
    ....d..ed..d....
    ....d.ede.de....
    .....ddde.dd....
    ......cdd.dc....
    ......cddcd.....
    .......cdc......
    ................
    ................
    ................`,
    F,
  ),
  px(
    `
    ................
    ................
    ................
    ................
    ................
    ................
    ......e.........
    ...e..e...e.....
    ...d.ed..ed.....
    ...dedd.edd.....
    ....ddc.dd......
    .....dcdcd......
    ......ccc.......
    ................
    ................
    ................`,
    F,
  ),
];

// ---- stone and wood props -------------------------------------------------------------------

const ST = {
  '0': 'ink',
  '1': 'slate-dark',
  '2': 'slate',
  '3': 'stone',
  '4': 'stone-light',
  '5': 'bone',
  z: SHADOW,
};
export const ROCKS: Pixmap[] = [
  px(
    `
    ................
    ................
    ................
    ................
    ......4444......
    .....4453334....
    ....443333332...
    ....43333333322.
    ....3333333222..
    ....33332222....
    .....2222111....
    ......z1111.....
    ......zzzzz.....
    ................
    ................
    ................`,
    ST,
  ),
  px(
    `
    ................
    ................
    ................
    ................
    ................
    ................
    ........44......
    ...44..4532.....
    ..4533.4332.....
    ..4333.3222.....
    ..3322..211.....
    ...zz...zz......
    ................
    ................
    ................
    ................`,
    ST,
  ),
];
export const BIG_ROCK: Pixmap = px(
  `
  ................................
  ................................
  ..........44444.................
  ........44455333444.............
  .......4455333333334............
  ......44533333333333322.........
  .....4453333333333333322........
  .....433333333332233333322......
  .....33333333332222333332222....
  ....333333333222222333222221....
  ....3333332222222222222221111...
  .....22222222222222211111111....
  ......1111111111111111111.......
  .......zzzzzzzzzzzzzzzzz........
  ................................
  ................................`,
  ST,
);

const WD = {
  A: 'bark-dark',
  B: 'bark',
  C: 'timber',
  D: 'oak',
  E: 'honey',
  F: 'straw',
  '0': 'ink',
  z: SHADOW,
  g: 'gold',
  v: 'lantern',
  s: 'ochre-dark',
  x: 'cream',
  '1': 'slate-dark',
  '2': 'slate',
  '3': 'stone',
  '4': 'stone-light',
  '5': 'bone',
  i: 'water',
  j: 'water-light',
  h: 'river',
  k: 'foam',
  n: 'brick',
  m: 'brick-dark',
  w: 'wine',
  r: 'peach',
  q: 'ember',
};

export const STUMP: Pixmap = px(
  `
  ................
  ................
  ................
  ................
  ................
  .....EEEEEE.....
  ....EEDDDDEE....
  ....EDDCCDDE....
  ....EDDCCDDE....
  ....BEDDDDEB....
  ....BBEEEEBB....
  ....ABBBBBBA....
  ....ABBBBBBA....
  ...AABBBBBBAA...
  ....zzzzzzzz....
  ................`,
  WD,
);

/** Fence pieces by 4-bit connection mask (N=1 E=2 S=4 W=8). */
export function fence(mask: number): Pixmap {
  const p = blank(16, 16);
  const post = px(
    `
    ................
    ......EDDA......
    ......EDDA......
    ......EDDA......
    ......EDDA......
    ......EDDA......
    ......EDDA......
    ......EDDA......
    ......EDDA......
    ......EDDA......
    ......EDDA......
    ......EDDA......
    ......EDDA......
    ......AAAA......
    ......zzzz......
    ................`,
    WD,
  );
  const railE = px(
    `
    ................
    ................
    ................
    ................
    ..........EEEEEE
    ..........DDDDDD
    ..........BBBBBB
    ................
    ................
    ..........EEEEEE
    ..........DDDDDD
    ..........BBBBBB
    ................
    ................
    ................
    ................`,
    WD,
  );
  const railS = px(
    `
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    .......DD.......
    .......DB.......
    .......DB.......`,
    WD,
  );
  const railN = px(
    `
    .......DB.......
    .......DB.......
    .......DB.......
    .......DB.......
    .......DB.......
    .......DB.......
    .......DB.......
    .......DB.......
    .......DB.......
    .......DB.......
    .......DB.......
    .......DB.......
    .......DB.......
    .......DB.......
    .......DB.......
    .......DB.......`,
    WD,
  );
  if (mask & 1) blit(p, railN, 0, 0);
  if (mask & 4) blit(p, railS, 0, 0);
  blit(p, post, 0, 0);
  if (mask & 2) blit(p, railE, 0, 0);
  if (mask & 8) blit(p, flipH(railE), 0, 0);
  return p;
}

export const LAMP_POST: Pixmap = px(
  `
  .......11.......
  ......1gg1......
  .....1gvvg1.....
  .....gvxvvg.....
  .....gvvvvg.....
  .....gvvvvg.....
  .....1gvvg1.....
  ......1gg1......
  .......11.......
  .......12.......
  .......12.......
  .......12.......
  .......12.......
  .......12.......
  .......12.......
  .......12.......
  .......12.......
  .......12.......
  .......12.......
  .......12.......
  .......12.......
  .......12.......
  .......12.......
  .......12.......
  .......12.......
  .......12.......
  ......1122......
  .....112222.....
  .....111111.....
  .....zzzzzz.....
  ................
  ................`,
  WD,
);

export const WELL: Pixmap = px(
  `
  ................................
  ..............mnnm..............
  ...........mnnnnnnnnm...........
  ........mnnnnnnnnnnnnnnm........
  .....mnnnnnnnnnnnnnnnnnnnnm.....
  ..mnnnnnnnnnnnnnnnnnnnnnnnnnnm..
  .wwwwwwwwwwwwwwwwwwwwwwwwwwwwww.
  ......EDA................EDA....
  ......EDA................EDA....
  ......EDA.....CCCCCCC....EDA....
  ......EDA.....C.......C..EDA....
  ......EDA.....C.......C..EDA....
  ......EDA.....C..EEE..C..EDA....
  ......EDA........DDD.....EDA....
  ......EDA........ADA.....EDA....
  ......EDA................EDA....
  ......EDA................EDA....
  .....4444444444444444444444.....
  ...44533333333333333333335344...
  ..4533333444444444444333333534..
  ..433333hhhhhhhhhhhhhhhh33333324
  ..43333hhhhiiiiiiiiiihhhh3333322
  ..43333hhhiiiijjiiiiiihhh3333322
  ..43333hhhhiiiiiiiiiihhhh3333322
  ..433333hhhhhhhhhhhhhhhh33333222
  ..43333333333333333333333333222.
  ..43333333333333333333333332222.
  ..333222333222333222333222222...
  ..222222222222222222222222221...
  ...111111111111111111111111.....
  ....zzzzzzzzzzzzzzzzzzzzzz......
  ................................`,
  WD,
);

/** The Ledger Bin, 32×16: a strongbox with brass bands and the open ledger on its lid. */
export const LEDGER_BIN: Pixmap = px(
  `
  ..........555555555555..........
  .........5xxxxx1xxxxx5..........
  .........5xxxxx1xxxxx5..........
  .........5x11xx1xx11x5..........
  ...AAAAAAnnnnnnnnnnnnnnAAAAAA...
  ..AEEEEEEEgEEEEEEEEEEgEEEEEEEA..
  ..ADDDDDDDgDDDDDDDDDDgDDDDDDDA..
  ..ADDDDDDDgDDDDDDDDDDgDDDDDDDA..
  ..ACCCCCCCgCCCCCCCCCCgCCCCCCCA..
  ..ADDDDDDDgDDDDDDDDDDgDDDDDDDA..
  ..ADDDDDDDgDDDDDDDDDDgDDDDDDDA..
  ..ACCCCCCCgCCCCCCCCCCgCCCCCCCA..
  ..ABBBBBBBsBBBBBBBBBBsBBBBBBBA..
  ..AAAAAAAAAAAAAAAAAAAAAAAAAAAA..
  ..zzzzzzzzzzzzzzzzzzzzzzzzzzzz..
  ................................`,
  WD,
);

export const MAILBOX: Pixmap = px(
  `
  ................
  ................
  ................
  ................
  ....mmmmmmm.....
  ...mnnnnnnnmg...
  ...mnnnnnnnmg...
  ...mn55555nmg...
  ...mnnnnnnnmg...
  ...mnnnnnnnm....
  ...mmmmmmmmm....
  ......EDA.......
  ......EDA.......
  ......EDA.......
  ......EDA.......
  ......EDA.......
  ......EDA.......
  ......EDA.......
  ......EDA.......
  ......EDA.......
  ......EDA.......
  ......EDA.......
  ......EDA.......
  ......EDA.......
  ......EDA.......
  ......EDA.......
  ......EDA.......
  .....AAAAA......
  ......zzz.......
  ................
  ................
  ................`,
  WD,
);

export function signpost(kind: 'lines' | 'coin' | 'fish' = 'lines'): Pixmap {
  const face = kind === 'coin' ? '...gvg...' : kind === 'fish' ? '.0..0.00.' : '.00000...';
  const face2 = kind === 'coin' ? '...gvg...' : kind === 'fish' ? '.000000..' : '.0000....';
  return px(
    `
    ................
    ................
    ...AAAAAAAAAAA..
    ..AEEEEEEEEEEEA.
    ..AEDDDDDDDDDDA.
    ..AED${face}A.
    ..AEDDDDDDDDDDA.
    ..AED${face2}A.
    ..AEDDDDDDDDDDA.
    ..ACCCCCCCCCCCA.
    ...AAAAAAAAAAA..
    .......EDA......
    .......EDA......
    .......EDA......
    .......EDA......
    .......EDA......
    .......EDA......
    .......EDA......
    .......EDA......
    .......EDA......
    .......EDA......
    .......EDA......
    .......EDA......
    .......EDA......
    .......EDA......
    .......EDA......
    .......EDA......
    .......EDA......
    ......AAAAA.....
    .......zzz......
    ................
    ................`,
    WD,
  );
}

export const BARREL: Pixmap = px(
  `
  ................
  ................
  ....AAAAAAAA....
  ...AEEEEEEEEA...
  ...ADDDDDDDDA...
  ...A11111111A...
  ...ADDCDDCDDA...
  ...ADDCDDCDDA...
  ...ADDCDDCDDA...
  ...ADDCDDCDDA...
  ...A11111111A...
  ...ADDCDDCDDA...
  ...ABBBBBBBBA...
  ....AAAAAAAA....
  ....zzzzzzzz....
  ................`,
  WD,
);
export const CRATE: Pixmap = px(
  `
  ................
  ................
  ..AAAAAAAAAAAA..
  ..AEDDDDDDDDEA..
  ..ADEDDDDDDEDA..
  ..ADDEDDDDEDDA..
  ..ADDDEDDEDDDA..
  ..ADDDDEEDDDDA..
  ..ADDDDEEDDDDA..
  ..ADDDEDDEDDDA..
  ..ADDEDDDDEDDA..
  ..ADEDDDDDDEDA..
  ..ACEDDDDDDECA..
  ..AAAAAAAAAAAA..
  ..zzzzzzzzzzzz..
  ................`,
  WD,
);
export const HAY: Pixmap = px(
  `
  ................
  ................
  ................
  ...ssssssssss...
  ..sFFFvFFFvFFFs.
  ..sFBFFFFFFBFFs.
  ..svBvvvvvvBvvs.
  ..sFBFFFFFFBFFs.
  ..sFBFvFFFvBFFs.
  ..svBvvvvvvBvvs.
  ..sFBFFFFFFBFFs.
  ..sgBgggggggggs.
  ..ssssssssssss..
  ..zzzzzzzzzzzz..
  ................
  ................`,
  WD,
);
export const BENCH: Pixmap = px(
  `
  ................................
  ................................
  ................................
  ...AAAAAAAAAAAAAAAAAAAAAAAAAA...
  ..AEEEEEEEEEEEEEEEEEEEEEEEEEEA..
  ..ADDDDDDDDDDDDDDDDDDDDDDDDDDA..
  ..ACCCCCCCCCCCCCCCCCCCCCCCCCCA..
  ..AEEEEEEEEEEEEEEEEEEEEEEEEEEA..
  ..ADDDDDDDDDDDDDDDDDDDDDDDDDDA..
  ..ACCCCCCCCCCCCCCCCCCCCCCCCCCA..
  ...AAAAAAAAAAAAAAAAAAAAAAAAAA...
  ....1A..................A1......
  ....1A..................A1......
  ....1A..................A1......
  ....zz..................zz......
  ................................`,
  WD,
);
export const FLOWER_BOX: Pixmap = px(
  `
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ...q..r.v..q....
  ..qdq.d.dv.dq...
  .AAAAAAAAAAAAAA.
  .AEEEEEEEEEEEEA.
  .ADDDDDDDDDDDDA.
  .ACCCCCCCCCCCCA.
  .AAAAAAAAAAAAAA.
  ................
  ................`,
  { ...WD, d: 'grass', v: 'lantern' },
);
export const TROUGH: Pixmap = px(
  `
  ................................
  ................................
  ................................
  ................................
  ..AAAAAAAAAAAAAAAAAAAAAAAAAAAA..
  .AEEEEEEEEEEEEEEEEEEEEEEEEEEEEA.
  .ADiiiiiiiiijjiiiiiiiiiiiiiiiDA.
  .ADiiiiiiiiiiiiiiiiiijjiiiiiiDA.
  .ADhhhhhhhhhhhhhhhhhhhhhhhhhhDA.
  .ACCCCCCCCCCCCCCCCCCCCCCCCCCCCA.
  .ABBBBBBBBBBBBBBBBBBBBBBBBBBBBA.
  ..AAAAAAAAAAAAAAAAAAAAAAAAAAAA..
  ...1A......................A1...
  ...zz......................zz...
  ................................
  ................................`,
  WD,
);

/** Stepping stones laid on a ford tile. */
export const FORD_STONES: Pixmap = px(
  `
  ................
  ................
  ..44............
  .4533...........
  .3322.....44....
  ..hh.....4533...
  .........3322...
  ..........hh....
  ....44..........
  ...4533.........
  ...3322.........
  ....hh......44..
  ...........4533.
  ...........3322.
  ............hh..
  ................`,
  WD,
);

export const PIER_POST: Pixmap = px(
  `
  ................
  ................
  ......EDDA......
  .....EDDDDA.....
  .....EDDDDA.....
  .....BBBBBB.....
  .....EDDDDA.....
  .....EDDDDA.....
  .....EDDDDA.....
  .....EDDDDA.....
  .....EDDDDA.....
  .....EDDDDA.....
  .....EDDDDA.....
  .....hhhhhh.....
  ................
  ................`,
  WD,
);

export const NET: Pixmap = px(
  `
  ................
  .AAAAAAAAAAAAAA.
  .A.E...E...E..A.
  ..E.E.E.E.E.E...
  ...E...E...E....
  ..E.E.E.E.E.E...
  .E...E...E...E..
  ..E.E.E.E.E.E...
  ...E...E...E....
  ..E.E.E.E.E.E...
  ...E...E...E....
  ....E.E.E.E.....
  .....E...E......
  ......E.E.......
  ................
  ................`,
  WD,
);

/** Paper lantern on a short post for the Lantern Drift site. */
export const LANTERN_POST: Pixmap = px(
  `
  ................
  .......AA.......
  ......qrrq......
  .....qrxrrq.....
  .....qrrrrq.....
  .....qrrrrq.....
  .....wqrrqw.....
  ......wqqw......
  .......AA.......
  .......DB.......
  .......DB.......
  .......DB.......
  .......DB.......
  .......DB.......
  ......AAAA......
  .......zz.......`,
  WD,
);

/** The Vault entrance in the Old Exchange cellar: a stone arch over steps going down. */
export const VAULT_ARCH: Pixmap = px(
  `
  ................................
  ...........444444444............
  .........44433gvg33444..........
  ........4433333g333334..........
  .......443333333333333344.......
  ......4433333333333333333.......
  ......43332222222222233334......
  .....4333222111111112223334.....
  .....433222111111111122333.4....
  .....43322111111111111223334....
  .....4332211111111111122333.....
  .....43322111111111111223334....
  .....4332211111111111122333.....
  .....43322111111111111223334....
  .....4332211111111111122333.....
  .....43322111111111111223334....
  .....4332211111111111122333.....
  .....43322100000000001223334....
  .....4332210000000000122333.....
  .....43322100000000001223334....
  .....4332210000000000122333.....
  .....43322100000000001223334....
  .....4332212222222222122333.....
  .....43322133333333331223334....
  .....4332212222222222122333.....
  .....43322133333333331223334....
  .....4332212222222222122333.....
  .....43333333333333333333334....
  .....33333333333333333333333....
  .....22222222222222222222222....
  .....zzzzzzzzzzzzzzzzzzzzzzz....
  ................................`,
  WD,
);

/** Ansel's ferry, 48×32, moored bow to the east. */
export const BOAT: Pixmap = px(
  `
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ..........................................gg....
  .........................................gvvg...
  ..........AAAAAAAAAAAAAAAAAAAAAAAAAA......gvvg..
  ........AADDDDDDDDDDDDDDDDDDDDDDDDDDAA.....gg...
  ......AADDDCCCCCCCCCCCCCCCCCCCCCCCCDDDAA...AA...
  .....ADDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDAAAAA...
  ....ADDDCCCCEEEEEECCCCCCCCEEEEEECCCCCCDDDDDDA...
  ....ADDCCCCCDDDDDDCCCCCCCCDDDDDDCCCCCCCCDDDDA...
  ....ADDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDA....
  ....AEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA.....
  .....AEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEA......
  ......ADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA.......
  .......ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA........
  ........AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.........
  ......kk..........kk................kk..........
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................
  ................................................`,
  WD,
);

/** The derelict windmill on the Mill Lot: tower 64×80 (walls layer) and sails 64×64 (above). */
export function windmillTower(): Pixmap {
  const p = blank(64, 80);
  fillEllipse(p, 32, 78, 20, 3, SHADOW);
  // stone base, then boarded timber upper, then a dark conical cap
  for (let y = 16; y < 78; y++) {
    const t = (y - 16) / 62;
    const half = 10 + t * 12;
    for (let x = 0; x < 64; x++) {
      const dx = x + 0.5 - 32;
      if (Math.abs(dx) > half) continue;
      const side = dx / half;
      const upper = y < 44;
      let shade: string;
      if (upper) shade = side < -0.35 ? 'honey' : side > 0.4 ? 'timber' : 'oak';
      else shade = side < -0.35 ? 'stone-light' : side > 0.4 ? 'slate' : 'stone';
      if (!upper && (y % 4 === 3 || ((x + (Math.floor(y / 4) % 2) * 3) % 6 === 0 && y % 4 !== 3)))
        shade = 'slate-dark';
      if (upper && y % 5 === 4) shade = 'bark';
      if (Math.abs(dx) > half - 1) shade = upper ? 'bark-dark' : 'ink';
      set(p, x, y, shade);
    }
  }
  // cap
  for (let y = 4; y < 18; y++) {
    const half = ((y - 2) / 16) * 12;
    for (let x = 0; x < 64; x++) {
      const dx = x + 0.5 - 32;
      if (Math.abs(dx) > half) continue;
      set(p, x, y, dx < -half * 0.4 ? 'bark' : dx > half * 0.5 ? 'ink' : 'bark-dark');
    }
  }
  // boarded window and door
  blit(p, px(`AAAAAAAA\nADDBDDBA\nABBDBBDA\nADDBDDBA\nAAAAAAAA`, WD), 28, 28);
  blit(
    p,
    px(
      `.AAAAAA.\nABBBBBBA\nABDDDDBA\nABDDDDBA\nABDDDDBA\nABDDDDBA\nABDgDDBA\nABDDDDBA\nABDDDDBA\nAAAAAAAA`,
      WD,
    ),
    28,
    67,
  );
  return p;
}

export function windmillSails(): Pixmap {
  const p = blank(64, 64);
  const cx = 32;
  const cy = 32;
  for (let y = 0; y < 64; y++) {
    for (let x = 0; x < 64; x++) {
      const dx = x + 0.5 - cx;
      const dy = y + 0.5 - cy;
      for (const a of [Math.PI / 4, (3 * Math.PI) / 4, (5 * Math.PI) / 4, (7 * Math.PI) / 4]) {
        const u = dx * Math.cos(a) + dy * Math.sin(a);
        const v = -dx * Math.sin(a) + dy * Math.cos(a);
        if (u < 5 || u > 30) continue;
        if (v >= -1 && v < 1) set(p, x, y, 'timber');
        else if (v >= 1 && v < 8)
          set(p, x, y, Math.floor(u) % 6 === 0 || v > 6.5 ? 'bark' : 'straw');
      }
    }
  }
  fillCircle(p, cx, cy, 3.5, 'bark-dark');
  return p;
}

/** The Town Hall's bell cupola, 16×32, sits on the roof ridge. */
export const CUPOLA: Pixmap = px(
  `
  .......gg.......
  ......1gg1......
  .....11111......
  ....1222221.....
  ...122222221....
  ..12222222221...
  .1222222222221..
  ..4444444444....
  ..4555005554....
  ..4550000554....
  ..455000055g....
  ..4550gg0554....
  ..4550gg0554....
  ..4555005554....
  ..4444444444....
  ..3333333333....
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................`,
  WD,
);

export const CLOCK: Pixmap = px(
  `
  ................
  .....111111.....
  ....11555511....
  ...1555555551...
  ...1550555551...
  ..155555555551..
  ..155555055551..
  ..155550g55551..
  ..155555555551..
  ..155555555551..
  ...1555555551...
  ...1550555551...
  ....11555511....
  .....111111.....
  ................
  ................`,
  WD,
);

export const PLAQUE: Pixmap = px(
  `
  ................
  ................
  ................
  ................
  ...ssssssssss...
  ..sgvvvvvvvvgs..
  ..sgvsssssvvgs..
  ..sgvvvvvvvvgs..
  ..sgvsssssvvgs..
  ..sggggggggggs..
  ...ssssssssss...
  ................
  ................
  ................
  ................
  ................`,
  WD,
);

/** Stone steps in front of a door, on the ground tile below it. */
export const STEPS: Pixmap = px(
  `
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ...4444444444...
  ...3333333332...
  ..444444444444..
  ..333333333332..
  ..222222222222..
  ................
  ................
  ................`,
  WD,
);

export function previewObjects(): Pixmap[] {
  return [
    oak(0),
    pine(),
    fruitTree('ember'),
    fruitTree('lantern', 1),
    bush(),
    ...FLOWERS,
    ...TUFTS,
    ...ROCKS,
    BIG_ROCK,
    STUMP,
    fence(0),
    fence(2 | 8),
    fence(1 | 4),
    fence(2 | 4),
    fence(1 | 2 | 4 | 8),
    LAMP_POST,
    WELL,
    LEDGER_BIN,
    MAILBOX,
    signpost(),
    signpost('coin'),
    BARREL,
    CRATE,
    HAY,
    BENCH,
    FLOWER_BOX,
    TROUGH,
    FORD_STONES,
    PIER_POST,
    NET,
    LANTERN_POST,
    VAULT_ARCH,
    BOAT,
    windmillTower(),
    windmillSails(),
    CUPOLA,
    CLOCK,
    PLAQUE,
    STEPS,
  ];
}

export const _o = { stack, fillRect, shaded };
