import { CardV2, type CardV2 as Card } from '@agent-town/schema';
import { ROLES, type Role } from './roles.ts';

/** Build the Character Card V2 for a sim role (PROMPT.md §5.1–5.2 field mapping). */
export function cardForRole(r: Role): Card {
  const permissions = r.trades
    ? {
        auto: ['read_market_data', 'post_comment', 'submit_report'],
        needs_mayor: ['place_order', 'modify_order', 'cancel_order', r.permission.action],
        needs_user: [
          'increase_allocation',
          'trade_new_asset_class',
          'use_leverage',
          'trade_outside_market_hours',
        ],
        forbidden: [
          'withdraw_funds',
          'change_own_limits',
          'disable_logging',
          'contact_external_parties',
        ],
      }
    : {
        auto: ['read_market_data', 'post_comment', 'submit_report'],
        needs_mayor: [r.permission.action],
        needs_user: ['increase_allocation'],
        forbidden: [
          'withdraw_funds',
          'change_own_limits',
          'disable_logging',
          'contact_external_parties',
          'place_order',
        ],
      };
  return CardV2.parse({
    spec: 'chara_card_v2',
    spec_version: '2.0',
    data: {
      name: r.name,
      description: r.description,
      personality: r.personality,
      scenario: r.scenario,
      first_mes: r.first_mes,
      mes_example: `<START>\n{{user}}: How is the desk?\n{{char}}: ${r.comments[0]}\n<START>\n{{user}}: Anything to report?\n{{char}}: ${r.comments[1]}`,
      creator_notes: 'Mock-fleet fixture generated by packages/sim; never a real agent.',
      system_prompt: '',
      post_history_instructions: '',
      alternate_greetings: [r.catchphrases[0]],
      tags: ['trading-firm', r.department, r.callsign.toLowerCase(), 'sim'],
      creator: 'packages/sim',
      character_version: '1.0',
      extensions: {
        agent_town: {
          schema_version: '1.1',
          kind: 'agent',
          id: r.id,
          task_role: r.task_role,
          business: 'trading-firm',
          department: r.department,
          reports_to: 'mayor',
          model: {
            provider: 'sim',
            name: 'mock-fleet',
            intelligence_tier: r.tier === 'brain' ? 'high' : r.tier === 'staff' ? 'medium' : 'low',
            runs_on: 'local',
          },
          risk_profile: r.trades ? 'risk-moderate' : 'none',
          stake: r.trades
            ? {
                allocation_pct: r.callsign === 'TRADER' ? 30 : 0,
                hard_cap_pct: r.callsign === 'TRADER' ? 30 : 0,
                currency: 'USD',
              }
            : undefined,
          limits: {
            max_position_pct_of_allocation: 10,
            max_daily_loss_pct_of_allocation: 2,
            max_drawdown_pct_of_allocation: 8,
            max_orders_per_hour: r.trades ? 20 : 0,
            cooldown_after_loss_streak: { losses: 3, minutes: 60 },
          },
          permissions,
          reporting: {
            heartbeat_sec: 15,
            status_report: 'hourly',
            daily_summary: '16:30 America/New_York',
          },
          endpoint: {
            protocol: 'webhook',
            url: `http://sim.local/${r.id}`,
            auth: 'bearer:env:SIM_FLEET_TOKEN',
          },
          metrics: [{ key: r.metric.key, label: r.metric.label, type: r.metric.type }],
          visual: {
            portrait: `assets/tallyford/portraits/${r.id}.png`,
            sprite: `characters:${r.id}`,
            desk_style: r.desk_style,
            palette_accent: r.palette_accent,
            layers: { ...r.look },
          },
          voice: {
            comment_style: 'smart-quip',
            comment_frequency: 'on_events_and_every_20_min_max',
            catchphrases: [...r.catchphrases],
            tts_voice_id: null,
          },
          lore: {
            origin: null,
            joined: null,
            skills: {},
            trust_hearts: {},
            quests_done: [],
            memories: [],
          },
        },
      },
    },
  });
}

export function allCards(): Card[] {
  return ROLES.map(cardForRole);
}
